export enum questionsActionTypes {
    LOAD_QUESTIONS = "LOAD_QUESTIONS",
    SET_QUESTIONS = "SET_QUESTIONS",
    LOAD_MORE_QUESTIONS = "LOAD_MORE_QUESTIONS",
    SET_LOADING = "SET_LOADING",
    SET_HAS_MORE = "SET_HAS_MORE",
  }
  